services:
  front:
    image: salesportalwasmapp
    build:
      context: .
      dockerfile: ./src/BlazorWasmApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9001:80"
    depends_on:
      - adapter
  adapter:
    image: crmadapterwebapi
    build:
      context: .
      dockerfile: ./src/CrmAdapterWebApi/Dockerfile
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - Logging__LogLevel__Devpro=Debug
      - AllowedOrigins__0=http://localhost:9001
      - Application__IsHttpsRedirectionEnabled=false
      - Application__IsOpenTelemetryEnabled=true
      - Application__IsSwaggerEnabled=true
      - CrmDataWebApi__Url=http://data:8080
      - OpenTelemetry__CollectorEndpoint=http://otelcollector:4317
    ports:
      - "9002:8080"
    depends_on:
      - data
  data:
    image: crmdatawebapi
    build:
      context: .
      dockerfile: ./src/CrmDataWebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - Logging__LogLevel__Devpro=Debug
      - AllowedOrigins__0=http://localhost:9002
      - AllowedOrigins__1=http://adapter:9002
      - Application__IsHttpsRedirectionEnabled=false
      - Application__IsOpenTelemetryEnabled=true
      - Application__IsSwaggerEnabled=true
      - ConnectionStrings__MongoDbLocal=mongodb://mongodb:27017/?readPreference=primary&appname=SalesPortalCrmDataWebApi&directConnection=true&ssl=false
      - MongoDb__ConnectionStringName=MongoDbLocal
      - MongoDb__DatabaseName=crm_data_dev
      - OpenTelemetry__CollectorEndpoint=http://otelcollector:4317
    ports:
      - "9003:8080"
    depends_on:
      - mongodb
      - otelcollector
  otelcollector:
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - MONGODB_ENDPOINT=mongodb:27017
      # - MONGODB_USERNAME=
      # - MONGODB_PASSWORD=
    ports:
      - 1888:1888   # pprof extension
      - 8888:8888   # Prometheus metrics exposed by the collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - mongodb
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
