receivers:
  mongodb:
    hosts:
      - endpoint: ${env:MONGODB_ENDPOINT}
    # username: ${env:MONGODB_USERNAME}
    # password: ${env:MONGODB_PASSWORD}
    collection_interval: 60s
    initial_delay: 1s
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug/detailed:
    verbosity: detailed
  debug/normal:
    verbosity: normal

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/detailed]
    metrics:
      receivers: [otlp, mongodb]
      processors: [batch]
      exporters: [debug/normal]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/normal]
