# purpose: run Continuous Delivery / Packaging (package)
# actions:
#   - https://github.com/marketplace/actions/docker-login
#   - https://github.com/marketplace/actions/docker-metadata-action (TODO)
#   - https://github.com/marketplace/actions/build-and-push-docker-images (TODO)
# images:
#   - https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
# variables:
#   - DOCKERHUB_NAMESPACE
# secrets:
#   - DOCKERHUB_USERNAME
#   - DOCKERHUB_TOKEN

name: PKG

on:
  push:
    branches: ["main"]
    # tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build container images
        run: |
            docker build . --file src/BlazorWasmApp/Dockerfile --tag IMAGE_FOLDER/salesportal-wasmapp:${{ env.IMAGE_TAG }}
            docker build . --file src/CrmAdapterWebApi/Dockerfile --tag IMAGE_FOLDER/salesportal-crmadapterwebapi:${{ env.IMAGE_TAG }}
            docker build . --file src/CrmDataWebApi/Dockerfile --tag IMAGE_FOLDER/salesportal-crmdatawebapi:${{ env.IMAGE_TAG }}
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: $CONTAINER_REGITRY_DOMAIN
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to container registry
        run: |
          docker push $IMAGE_FOLDER/salesportal-wasmapp:${{ env.IMAGE_TAG }}
          docker push $IMAGE_FOLDER/salesportal-crmadapterwebapi:${{ env.IMAGE_TAG }}
          docker push $IMAGE_FOLDER/salesportal-crmdatawebapi:${{ env.IMAGE_TAG }}
      - name: Push latest tag to container registry
        run: |
          docker tag IMAGE_FOLDER/salesportal-wasmapp:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/salesportal-wasmapp:latest
          docker push IMAGE_FOLDER/salesportal-wasmapp:latest
          docker tag IMAGE_FOLDER/salesportal-crmadapterwebapi:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/salesportal-crmadapterwebapi:latest
          docker push IMAGE_FOLDER/salesportal-crmadapterwebapi:latest
          docker tag IMAGE_FOLDER/salesportal-crmdatawebapi:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/salesportal-crmdatawebapi:latest
          docker push IMAGE_FOLDER/salesportal-crmdatawebapi:latest
    env:
      CONTAINER_REGITRY_DOMAIN: docker.io
      IMAGE_FOLDER: ${{ vars.DOCKERHUB_NAMESPACE }}
      IMAGE_TAG: 1.0.${GITHUB_RUN_ID}
